version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: to_do_postgres
    environment:
      POSTGRES_DB: to_do_java
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: